--Importando dados de um arquvio
@ 'C:\Users\labsfiap\Desktop\Mastering_Relational_And_Non-Relational_Database\Primeiro_Semestre\Aula_05\script_modelo_pedido.sql';

-- Fazendo alterações das tabelas por erros do script do professor
ALTER TABLE CIDADE MODIFY NOM_CIDADE VARCHAR(40);
ALTER TABLE PEDIDO ADD STATUS VARCHAR(30);


//Fazendo os inserts que o professor enviou
INSERT INTO PAIS SELECT * FROM PF1788.PAIS;
INSERT INTO ESTADO SELECT * FROM PF1788.ESTADO;
INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;

--Realizando selects para ver se as tabelas já foram populadas ou não
SELECT * FROM PAIS;
SELECT * FROM ESTADO;
SELECT * FROM CIDADE;
SELECT * FROM TIPO_ENDERECO;
SELECT * FROM CLIENTE;
SELECT * FROM ENDERECO_CLIENTE;
SELECT * FROM USUARIO;
SELECT * FROM VENDEDOR;
SELECT * FROM PRODUTO;
SELECT * FROM PRODUTO_COMPOSTO;
SELECT * FROM TIPO_MOVIMENTO_ESTOQUE;
SELECT * FROM ESTOQUE;
SELECT * FROM ESTOQUE_PRODUTO;
SELECT * FROM CLIENTE_VENDEDOR;
SELECT * FROM MOVIMENTO_ESTOQUE;
SELECT * FROM PEDIDO;
SELECT * FROM HISTORICO_PEDIDO;
SELECT * FROM ITEM_PEDIDO;

COMMIT;